### PR TITLE
Fixed #1681: Metal runtime fails Xcode's "Metal API Validation" assertions

### LINKED ISSUE #1681: Metal runtime fails Xcode's "Metal API Validation" assertions
The Metal runtime triggers three different assertions when running with "Metal API Validation" enabled, indicating problems with at least three of the runtime's calls to Metal.

Metal API Validation is enabled by default when running inside Xcode (controlled by Product > Scheme > Edit Scheme… > Run > Options > Metal API Validation). It's ordinarily disabled when running outside Xcode, but can be enabled by setting `METAL_DEVICE_WRAPPER_TYPE=1`.

To reproduce the assertion failures, run the following command on a Mac:
```
HL_JIT_TARGET=host-metal METAL_DEVICE_WRAPPER_TYPE=1 make -i run_tests
```

Three assertion failures appear repeatedly:
```
MTLDebugComputeCommandEncoder.mm:475: failed assertion `length(4) must be a multiple of 16 bytes.'
MTLDebugBuffer.mm:163: failed assertion `didModifyRange: only applies when resourceOptions(0x0) & MTLResourceStorageModeMask(0xf0) == MTLResourceStorageModeManaged(0x10).  NOT MTLResourceStorageModeShared'
MTLDebugBlitCommandEncoder.mm:810: failed assertion `synchronizeResource: only applies when resourceOptions(0x0) & MTLResourceStorageModeMask(0xf0) == MTLResourceStorageModeManaged(0x10).  NOT MTLResourceStorageModeShared'
```

I'm working on fixing these issues in `metal.cpp`.

### PR DESCRIPTION
**Pull request by estollnitz**
Fixed assertions when calling `modifyRange` and `synchronizeResource` by first checking the Metal buffer's `storageMode` property to see if it's a managed resource. Related calls in `halide_metal_device_sync_internal` also move inside this check.

Fixed assertion when calling `setThreadgroupMemoryLength` by rounding shared memory size up to the next larger multiple of 16.

In addition, re-ordered the sequence of operations in `halide_metal_copy_to_device` so that the CPU memcpy from host to dev happens (if needed) before telling Metal to synchronize the buffer. It  worked when it was the other way around, but likely had a race condition lurking there.

Also added debug output to `device_copy::copy_memory` so we'll be able to tell when we reach a zero-copy solution.

### CODE REVIEW

File: src/runtime/metal.cpp [hunk 1]
```diff
@@ -88,29 +88,23 @@ struct NSRange {
...
-        (*method2)(encoder, synchronize_resource_sel, buffer);
-    }
+WEAK void synchronize_resource(mtl_blit_command_encoder *encoder, mtl_buffer *buffer) {
+    typedef void (*synchronize_resource_method)(objc_id obj, objc_sel sel, mtl_buffer *buffer);
+    synchronize_resource_method method = (synchronize_resource_method)&objc_msgSend;
+    (*method)(encoder, sel_getUid("synchronizeResource:"), buffer);
+}
+
+WEAK bool is_buffer_managed(mtl_buffer *buffer) {
+    typedef int (*storage_mode_method)(objc_id obj, objc_sel sel);
```
Comment (zvookin) [inline src/runtime/metal.cpp]: I believe the "storageMode" selector is only supported in iOS 9 and later. Thus this call needs to check if the method is supported before trying to call it. (The code will likely work as it stands because dispatching nonexistent methods returns nil, but depending on that is a bad idea and I believe it does log warning messages in certain execution contexts and possibly fails under stricter execution models or checker tools.) I think this is the only selector test still needed as if storageMode exists, all the other methods will exist as well.

Comment (estollnitz) [inline src/runtime/metal.cpp]: Thanks, Zalman. Good point... I'll correct this when I'm back in a couple of weeks.

**Comment by zvookin** [comment]
I decided to go ahead and merge this and make the selector fix immediately after.

**Comment by estollnitz** [comment]
Thanks, Zalman. Sorry I didn’t get around to it before going on vacation.

Minor question on your selector fix: do you want to re-use storage_mode_sel, rather than call sel_getUid("storageMode") a second time?

Eric

**Comment by zvookin** [comment]
Good call. Will fix shortly.

-Z-
