### PR TITLE
[vulkan] Fixes to address outstanding validation failures 

### LINKED ISSUE #8287: [vulkan] Parameter storage buffer alignment can fail validation
As discovered on `linux-worker-1` after we updated the Vulkan SDK to v1.3.283 running on an NVIDIA RTX 3070 w/driver 535.161.8.0:

`bilateral_grid_process: Structure id 712 decorated as BufferBlock for variable in Uniform storage class must follow relaxed storage buffer layout rules: member 0 contains an array with stride 4 not satisfying alignment to 8`

Other apps seem to fail with similar validation failures.

I'm not entirely sure how to handle alignment offsets within the storage buffer used to pass the parameters.  We assume they're all packed together, which apparently isn't a valid assumption.  So, we'll likely have to pad the buffer, and copy them into offsets that conform to the alignment.

### LINKED ISSUE #8291: [vulkan] bilateral_grid generates invalid float assignment from float2 value
```
> VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ./bilateral_grid/bilateral_grid_process ./bilateral_grid/gray.png ./bilateral_grid/out.png 0.1 10
UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x134023018, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 716 decorated as BufferBlock for variable in Uniform storage class must follow relaxed storage buffer layout rules: member 0 contains an array with stride 4 not satisfying alignment to 8
  %k2_buffer_block2 = OpTypeStruct %_runtimearr_v2float

    Objects: 1
        [0] 0x134023018, type: 3, name: NULL
VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06719(ERROR / SPEC): msgNum: 1610793953 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06719 ] Object 0: handle = 0x134023018, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6002c3e1 | After specialization was applied, VkShaderModule 0xfab64d0000000002[] does not contain valid spirv for stage VK_SHADER_STAGE_COMPUTE_BIT. The Vulkan spec states: The shader code used by the pipeline must be valid as described by the Khronos SPIR-V Specification after applying the specializations provided in pSpecializationInfo, if any, and then converting all specialization constants into fixed constants (https://vulkan.lunarg.com/doc/view/1.3.231.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06719)
    Objects: 1
        [0] 0x134023018, type: 3, name: NULL
VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06719(ERROR / SPEC): msgNum: 1610793953 - Validation Error: [ VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06719 ] Object 0: handle = 0x134023018, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6002c3e1 | After specialization was applied, VkShaderModule 0xfab64d0000000002[] does not contain valid spirv for stage VK_SHADER_STAGE_COMPUTE_BIT. The Vulkan spec states: The shader code used by the pipeline must be valid as described by the Khronos SPIR-V Specification after applying the specializations provided in pSpecializationInfo, if any, and then converting all specialization constants into fixed constants (https://vulkan.lunarg.com/doc/view/1.3.231.1/mac/1.3-extensions/vkspec.html#VUID-VkPipelineShaderStageCreateInfo-pSpecializationInfo-06719)
    Objects: 1
        [0] 0x134023018, type: 3, name: NULL
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:145:121: error: assigning to 'float' from incompatible type 'float2' (vector of 2 'float' values)
    k2_blurx._m0[(((((_819 * 32) + _739) * 2) - _823) / 2) + _823] = float2(k2_blurz._m0[_752.x], k2_blurz._m0[_752.y]) + ((float2(k2_blurz._m0[_763.x], k2_blurz._m0[_763.y]) * float2(4.0)) + ((float2(k2_blurz._m0[_776.x], k2_blurz._m0[_776.y]) * float2(6.0)) + (float2(k2_blurz._m0[_788.x], k2_blurz._m0[_788.y]) + (float2(k2_blurz._m0[_799.x], k2_blurz._m0[_799.y]) * float2(4.0)))));
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
program_source:159:121: error: assigning to 'float' from incompatible type 'float2' (vector of 2 'float' values)
    k2_blurx._m0[(((((_908 * 32) + _739) * 2) - _912) / 2) + _912] = float2(k2_blurz._m0[_843.x], k2_blurz._m0[_843.y]) + ((float2(k2_blurz._m0[_853.x], k2_blurz._m0[_853.y]) * float2(4.0)) + ((float2(k2_blurz._m0[_865.x], k2_blurz._m0[_865.y]) * float2(6.0)) + (float2(k2_blurz._m0[_877.x], k2_blurz._m0[_877.y]) + (float2(k2_blurz._m0[_887.x], k2_blurz._m0[_887.y]) * float2(4.0)))));
                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.

```

### LINKED ISSUE #8293: [vulkan] hist_filter generates invalid index pair
```
./VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation ./hist/hist_filter ./hist/rgba.png out.png                                             
UNASSIGNED-CoreValidation-Shader-InconsistentSpirv(ERROR / SPEC): msgNum: 7060244 - Validation Error: [ UNASSIGNED-CoreValidation-Shader-InconsistentSpirv ] Object 0: handle = 0x13a042218, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x6bbb14 | SPIR-V module not valid: Structure id 490 decorated as BufferBlock for variable in Uniform storage class must follow relaxed storage buffer layout rules: member 0 contains an array with stride 4 not satisfying alignment to 8
  %k8_buffer_block1 = OpTypeStruct %_runtimearr_v2int

    Objects: 1
        [0] 0x13a042218, type: 3, name: NULL
[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):
program_source:183:57: error: member reference base type 'device int' is not a structure or union
    k8_cdf_global_wrapper_0_0[_543.x] = k8_cdf._m0[_537].x;
                                        ~~~~~~~~~~~~~~~~^~
program_source:184:57: error: member reference base type 'device int' is not a structure or union
    k8_cdf_global_wrapper_0_0[_543.y] = k8_cdf._m0[_537].y;
                                        ~~~~~~~~~~~~~~~~^~

```

### PR DESCRIPTION
**Pull request by derek-gerstmann**
- Fix ArrayStride for arrays of vectors bound to buffer blocks.
- Make a local copy of allocators to avoid dangling references during destruction
- Cleanup Vulkan Memory Allocator destruction to avoid duplicate calls to destroy block allocator

Fixes #8291
Fixes #8287 
Fixes #8293

### CODE REVIEW

**Comment by derek-gerstmann** [comment]
Fixes #8291

File: src/runtime/vulkan_memory.h [hunk 1]
```diff
@@ -161,13 +161,9 @@ int VulkanMemoryAllocator::destroy(void *user_context, VulkanMemoryAllocator *in
...
     }
-    const BlockAllocator::MemoryAllocators &allocators = instance->block_allocator->current_allocators();
+    BlockAllocator::MemoryAllocators allocators = instance->block_allocator->current_allocators();
     instance->destroy(user_context);
-    BlockAllocator::destroy(user_context, instance->block_allocator);
-    if (allocators.system.deallocate == nullptr) {
-        error(user_context) << "VulkanBlockAllocator: Unable to destroy instance! Missing system allocator interface!\n";
-        return halide_error_code_internal_error;
-    }
+    halide_abort_if_false(user_context, allocators.system.deallocate != nullptr);
```
Comment (steven-johnson) [inline src/runtime/vulkan_memory.h:166]: Is this really a crash-the-program error?

**Review by steven-johnson — APPROVED** [review]

File: src/runtime/vulkan_memory.h (hunk 1 above)
Comment (derek-gerstmann) [reply src/runtime/vulkan_memory.h]: Yeah, probably safer to revert back to the error message and return code.

**Comment by derek-gerstmann** [comment]
Okay, this is good to go.  I've been testing this on my local machine configs and this passes cleanly on Linux Ubuntu 22.04 w/Vulkan SDK v1.3.296 w/NVIDIA GeForce RTX 3070 TI.

**Comment by derek-gerstmann** [comment]
I'm also testing changes to avoid over-use of descriptor sets on resource constrained devices, but that'll be a larger PR.
