### PR TITLE
Fix infinite recursion in loop partitioning

### LINKED ISSUE #7742: Fuse a split with PredicateStores leads to infinite simplication
A simple repro:
```
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv) {
    Var x, y, x_outer, x_inner, y_x_inner_fused;
    Func f;
    f(x, y) = x + y;
    f.split(x, x_outer, x_inner, 2, TailStrategy::PredicateStores).fuse(y, x_inner, y_x_inner_fused);
    Pipeline p(f);
    p.realize({100, 100});
    return 0;
}
```

### PR DESCRIPTION
**Pull request by abadams**
Fixes #7742

### CODE REVIEW

**Review by steven-johnson — APPROVED** [review]
LGTM pending green

File: test/correctness/partition_loops.cpp [hunk 1]
```diff
@@ -3,49 +3,62 @@
...
 
+    // A loop partitioning bug from https://github.com/halide/Halide/issues/7742
+    {
+        Var x, y, x_outer, x_inner, y_x_inner_fused;
+        Func f;
+        f(x, y) = x + y;
+        f.split(x, x_outer, x_inner, 2, TailStrategy::PredicateStores).fuse(y, x_inner, y_x_inner_fused);
+        Pipeline p(f);
+        p.realize({100, 100});
+        return 0;
```
Comment (TH3CHARLie) [inline test/correctness/partition_loops.cpp:59]: the `return 0` here should be removed

Comment (abadams) [reply test/correctness/partition_loops.cpp]: Thanks, fixed
