### PR TITLE
Don't emit aligned loads to unaligned addresses

### LINKED ISSUE #6046: Halide tries to do aligned loads from unaligned buffers
This happens with strided loads with stride 3 in a complex test case I have. Looking at the relevant portion of CodeGen_LLVM, the alignment tags on the dense load appear to be bunk.

This is a pretty bad bug, because it causes hard-to-diagnose crashes inside compiled Halide pipelines (unless you know what you're looking for).

### PR DESCRIPTION
**Pull request by abadams**
Fixes #6046

### CODE REVIEW

**Review by dsharletg — APPROVED** [review]

**Review by alexreinking — APPROVED** [review]

**Comment by abadams** [comment]
Currently checking if it solves the more complex case I had...

**Comment by alexreinking** [comment]
Looks like arm64-linux-worker-1 might need to rebuild LLVM 13

**Comment by abadams** [comment]
Yes, it seems to have fixed my real failure cases.

File: test/correctness/align_bounds.cpp [hunk 1]
```diff
@@ -197,6 +197,29 @@ int main(int argc, char **argv) {
...
+    {
+        Func f, g;
+        Var x;
+
+        f(x) = x;
+
+        // Do strided loads of every possible alignment
+        Expr e = 0;
+        for (int i = -32; i <= 32; i++) {
+            e += f(3 * x + i);
```
Comment (dsharletg) [inline test/correctness/align_bounds.cpp:212]: I wonder if LLVM might rewrite this to one load plus a bunch of shuffles, which might hide alignment issues? Maybe not now, but it could later?

To avoid this, maybe it would be better to put a loop around the whole thing including the realize, loading one at a time.

**Review by alexreinking — APPROVED** [review]

**Comment by alexreinking** [comment]
Not sure what's going on with x86-64-osx-make. @steven-johnson can you take a look?

File: test/correctness/align_bounds.cpp (hunk 1 above)
Comment (steven-johnson) [reply test/correctness/align_bounds.cpp:212]: True, but if the test doesn't reliably test the thing we need testing, it doesn't matter how fast it is. (I guess if this works currently then it's ok, but might be worth capturing this thought in a comment if it breaks again.)

Comment (abadams) [reply test/correctness/align_bounds.cpp:212]: I also think the kind of transformation Dillon is talking about is vanishingly unlikely. We're codegenning three consecutive dense vector loads followed by a big shuffle. LLVM isn't going to change that to different loads followed by a different shuffle. The loads are already optimal.

Comment (abadams) [reply test/correctness/align_bounds.cpp:212]: If LLVM ever started doing that sort of transformation, we'd need to disable it anyway, because we have scheduling directives to do that and they would stop working.

**Comment by steven-johnson** [comment]
> Not sure what's going on with x86-64-osx-make. @steven-johnson can you take a look?

I think I fixed it, but can't retest this specific build because branch is closed and deleted. Will retry with another.
