### PR TITLE
Fix predicated load/store of one-lane vectors

### LINKED ISSUE #8922: Error in CodeGen_LLVM with predicated load/store of 1-lane vectors
When CodeGen_LLVM tries to codegen a predicated load or store involving a 1-lane vector (which happens any time the vector length in the IR is 1 modulo the native vector length), it raises an error because slice_vector turns 1-lane vectors into single elements via CreateExtractElement. This is incompatible with CreateMaskedStore and CreateMaskedLoad, which require a vector type. The simplest way to fix this is to just not convert these 1-lane vectors into elements.

Code to reproduce:

```
f1(x) = input(x) * 2;
f2(x) = select(x < 8, 0, f1(x)+f1(x+1));

f2.split(x, xo, xi, 8);
f1.compute_at(f2, xo).vectorize(x);
```

### PR DESCRIPTION
**Pull request by alexreinking**
Fixes #8922

### CODE REVIEW

File: test/correctness/predicated_store_load_single_lane.cpp [hunk 1]
```diff
@@ -0,0 +1,35 @@
...
+
+    ImageParam input(Float(32), 1);
+
+    f1(x) = input(x) * 2;
+    f2(x) = select(x < w, 0, f1(x) + f1(x + 1));
+
+    // This schedule creates a situation where f1 is computed with a
+    // vectorized loop that requires predicated loads/stores for the
+    // final single element.
+    f2.split(x, xo, xi, w);
```
Comment (mcourteaux) [inline test/correctness/predicated_store_load_single_lane.cpp:24]: Shouldn't you explicitly select a Predicated tail strategy? Auto might select guard with if?

File: test/correctness/predicated_store_load_single_lane.cpp [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+    f1.compute_at(f2, xo).vectorize(x);  // effective vector width = w + 1
```
Comment (mcourteaux) [inline test/correctness/predicated_store_load_single_lane.cpp:25]: Or in vectorize set the tail strategy?

File: test/correctness/predicated_store_load_single_lane.cpp (hunk 1 above)
Comment (abadams) [reply test/correctness/predicated_store_load_single_lane.cpp:24]: GuardWithIf currently generates a predicate, but yes it might be more future proof to use TailStrategy::Predicate here
