### PR TITLE
Large stack printer objects break llvm debuginfo

### LINKED ISSUE #4996: Windows buildbots hitting assertion failures in LLVM
We're seeing the following error on a few tests:

```
Assertion failed: AfterInsn && "Expected label after instruction", file C:\build_bot\worker\win-64-testbranch-1000\llvm-project\llvm\lib\CodeGen\AsmPrinter\DebugHandlerBase.cpp, line 136
```

These seem to occur in tests that are manually setting the `Target::Debug` feature, and they've been showing up in OpenCL and D3D12Compute.

CC @alexreinking: May be related to Day 1 changes to remove debug info.

### PR DESCRIPTION
**Pull request by abadams**
This fixes several test failures on master with expected-label-after-instruction 

I tracked the error down to instances of large StackPrinter objects in the d3d12 runtime. We probably shouldn't be making large stack allocations anyway, so I avoided these by in one case using malloc, and in the other case (tracing) using a global buffer guarded by a spinlock (trace was already using globals guarded by the same spinlock).

Fixes #4996

### CODE REVIEW

**Comment by steven-johnson** [comment]
Wow, that is a weird way for stack corruption to get reported.

File: src/runtime/d3d12compute.cpp [hunk 1]
```diff
@@ -86,40 +86,52 @@ class StackPrinter : public Printer<type, length> {
...
+        trace_scope___.lock();                                                                \
+        Printer<BasicPrinter, TRACE_BUF_SIZE>(user_context, trace_buf) << TRACEINDENT << msg; \
+        trace_scope___.unlock();                                                              \
+    }
 struct TraceLogScope {
-    TraceLogScope() {
-        while (__atomic_test_and_set(&indent_lock, __ATOMIC_ACQUIRE)) {
+    void *user_context;
+
+    void lock() {
```
Comment (steven-johnson) [inline src/runtime/d3d12compute.cpp:105]: nit: it's too bad we can't reuse the guts of ScopedSpinLock here somehow, rather than recaptitulating the __atomic calls

**Comment by abadams** [comment]
It's compiling it that fails. My guess is that large stack frames send llvm down a different path for debug info and that triggers the llvm bug.

File: src/runtime/d3d12compute.cpp [hunk 2]
```diff
@@ -86,40 +86,52 @@ class StackPrinter : public Printer<type, length> {
...
-// a halide_malloc failure, and user code should not affect debug-tracing
-#define trace(x) StackPrinter<4096, BasicPrinter>(x)
-
-static volatile ScopedSpinLock::AtomicFlag indent_lock = 0;
-static const char indent_pattern[] = "   ";
-static char indent[2048] = {};
-static int indent_end = 0;
-#define TRACEINDENT ((const char *)indent)
-#define TRACEPRINT(msg) trace(user_context) << TRACEINDENT << msg;
+static volatile ScopedSpinLock::AtomicFlag trace_indent_lock = 0;
```
Comment (steven-johnson) [inline src/runtime/d3d12compute.cpp:89]: nit: probably worth adding a comment here about why we are explicitly avoiding StackPrinter

Comment (abadams) [reply src/runtime/d3d12compute.cpp]: I just deleted StackPrinter entirely and made Printer use the stack when things are small instead.

File: src/runtime/d3d12compute.cpp (hunk 1 above)
Comment (abadams) [reply src/runtime/d3d12compute.cpp]: Good point. Now uses a ScopedSpinLock.

**Comment by abadams** [comment]
The errors in master were actually in opencl, not d3d12! But it's the same error for the same reason. I removed a large stack allocation and it seemed to heal it.

File: src/runtime/printer.h [hunk 3]
```diff
@@ -32,10 +32,18 @@ class Printer {
...
 
     Printer(void *ctx, char *mem = NULL)
         : user_context(ctx), own_mem(mem == NULL) {
-        buf = mem ? mem : (char *)halide_malloc(user_context, length);
+        if (mem != NULL) {
+            buf = mem;
+        } else if (length <= sizeof(scratch)) {
+            buf = scratch;
+        } else {
+            buf = (char *)malloc(length);
```
Comment (shoaibkamil) [inline src/runtime/printer.h:44]: Maybe add a comment explaining why not to use halide_malloc?  Otherwise someone will surely change this in a few weeks :)

**Comment by shoaibkamil** [comment]
LGTM, thanks for tracking this down!
