### PR TITLE
Fix issues in OpenGL backend

### LINKED ISSUE #4885: OpenGL tests all fail on macOS
While the OpenGL tests build on macOS, they do not run. They all crash with

```
Error: (at /Users/halidenightly/build_bot_new/worker/mac-64-1000/halide/test/opengl/varying.cpp:62)
The pipeline returned exit status -1 but halide_error was never called.
```

With the line of the error suitably replaced for the test.

### LINKED ISSUE #4937: GLSL app broken
The GLSL app is broken (and isn't built by the Makefile currently). When trying to build and test it on `cmake-modern`, we get the following error:

```
543: 1: Entering Pipeline halide_blur_glsl
543: 1: Target: x86-64-linux-avx-avx2-cuda-debug-no_runtime-opengl-sse41
543: 1:  Input Buffer input8: buffer(0, 0x0, 0x55d69f0db900, 0, uint8, {0, 12, 1}, {0, 32, 12}, {0, 3, 384})
543: 1:  Output Buffer blur_filter: buffer(0, 0x0, 0x55d69f0dbe00, 0, uint8, {0, 12, 1}, {0, 32, 12}, {0, 3, 384})
543: 1: In initialize_kernels
543: 1: Halide running on OpenGL 3.2
543: 1:   vertex_array_objects: yes
543: 1:   texture_rg: yes
543: 1:   have_texture_rgb8_rgba8: yes
543: 1:   texture_float: yes
543: 1: Compiling GLSL kernel (size = 375):
543: 1: GL_VERTEX_SHADER SOURCE:
543: 1: attribute vec4 _varyingf0_attrib;
543: 1: varying   vec4 _varyingf0;
543: 1: uniform ivec2 output_min;
543: 1: uniform ivec2 output_extent;
543: 1: void main() {
543: 1:     vec2 position = vec2(_varyingf0_attrib[0], _varyingf0_attrib[1]);
543: 1:     gl_Position = vec4(position, 0.0, 1.0);
543: 1:     vec2 texcoord = 0.5 * position + 0.5;
543: 1:     vec2 pixcoord = texcoord * vec2(output_extent.xy) + vec2(output_min.xy);
543: 1:     _varyingf0 = _varyingf0_attrib;
543: 1:     _varyingf0.xy = pixcoord;
543: 1: }
543: 1: GL_FRAGMENT_SHADER SOURCE:
543: 1: 
543: 1: // ll suffix in OpenCL is reserved for 128-bit integers.
543: 1: #if defined __OPENCL_VERSION__
543: 1: #define ADD_INT64_T_SUFFIX(x) x##l
543: 1: #define ADD_UINT64_T_SUFFIX(x) x##ul
543: 1: // HLSL doesn't have any suffixes.
543: 1: #elif defined HLSL_VERSION
543: 1: #define ADD_INT64_T_SUFFIX(x) x
543: 1: #define ADD_UINT64_T_SUFFIX(x) x
543: 1: #else
543: 1: #define ADD_INT64_T_SUFFIX(x) x##ll
543: 1: #define ADD_UINT64_T_SUFFIX(x) x##ull
543: 1: #endif
543: 1: Compiling GLSL kernel (size = 4241):
543: 1: Error: Internal error: argument type not supported
```

### PR DESCRIPTION
**Pull request by xndcn**
Fix some issues in OpenGL backend.

Fixes #4885
Fixes #4937

### CODE REVIEW

**Comment by xndcn** [comment]
Now all 20 OpenGL tests passed. Tested under Mac and Linux.

**Comment by steven-johnson** [comment]
LGTM pending green tests at https://github.com/halide/Halide/pull/5550

**Comment by alexreinking** [comment]
Will this fix #4937 (the glsl app)?

File: src/InjectOpenGLIntrinsics.cpp [hunk 1]
```diff
@@ -40,33 +40,41 @@ class InjectOpenGLIntrinsics : public IRMutator {
...
+            int dims = (call_args.size() - 2) / 2;
+            internal_assert(dims >= 1 && dims <= 3);
+
             vector<Expr> args(5);
             args[0] = call_args[0];  // "name"
             args[1] = call_args[1];  // name.buffer
 
             // Normalize first two coordinates.
-            for (size_t i = 0; i < 2; i++) {
+            for (size_t i = 0; i < std::min(dims, 2); i++) {
```
Comment (steven-johnson) [inline src/InjectOpenGLIntrinsics.cpp:51]: This triggers

```
InjectOpenGLIntrinsics.cpp:51:34: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]

             for (size_t i = 0; i < std::min(dims, 2); i++) {
```

For some compilers; please fix.

Comment (alexreinking) [reply src/InjectOpenGLIntrinsics.cpp:51]: It's probably simplest to rewrite as `for (int i ...)`.

Comment (xndcn) [reply src/InjectOpenGLIntrinsics.cpp]: Thanks! Sorry for that...

**Comment by xndcn** [comment]
> Will this fix #4937 (the glsl app)? https://github.com/halide/Halide/tree/master/apps/glsl

Tested under linux, and it (apps/glsl) looks good.

**Comment by alexreinking** [comment]
> > Will this fix #4937 (the glsl app)? https://github.com/halide/Halide/tree/master/apps/glsl
> 
> Tested under linux, and it (apps/glsl) looks good.

That's great! Would you please enable the app in apps/CMakeLists.txt?

**Comment by steven-johnson** [comment]
Waiting for the CMake update for apps/glsl; once that's in place, will re-run tests, and land if all good

**Comment by xndcn** [comment]
> Waiting for the CMake update for apps/glsl; once that's in place, will re-run tests, and land if all good

Sorry for my late...
Have update CMake for apps/glsl

**Comment by steven-johnson** [comment]
https://github.com/halide/Halide/pull/5564

**Comment by steven-johnson** [comment]
Note that apps/opengl_test is failing because it apparently requires X11 to be functional, which isn't the case on our buildbots

**Comment by alexreinking** [comment]
> apps/opengl_test

Do you mean apps/opengl_demo? or apps/glsl?

File: src/CodeGen_OpenGL_Dev.cpp [hunk 2]
```diff
@@ -134,7 +134,15 @@ Type CodeGen_GLSLBase::map_type(const Type &type) {
...
         } else if (type.is_uint() && type.bits() <= 32) {
-            result = UInt(32);
+            if (support_native_uint) {
+                result = UInt(32);
+            } else {
+                if (type.bits() == 32) {
+                    result = Int(32);
+                } else {
+                    result = Float(32);
+                }
```
[the remark this answers is not in the document]
Comment (steven-johnson) [reply src/CodeGen_OpenGL_Dev.cpp:144]: > > apps/opengl_test
> 
> Do you mean apps/opengl_demo? or apps/glsl?

https://buildbot.halide-lang.org/master/#/builders/25/builds/6

[the remark this answers is not in the document]
Comment (xndcn) [reply src/CodeGen_OpenGL_Dev.cpp]: @alexreinking Basically these code around `support_native_uint` exists before commit #60442cf9
Sorry I forgot the comments and have add those back. The idea about represent uint by int seems a compromise and may result in overflows and undefined behavior

File: src/CodeGen_OpenGL_Dev.cpp [hunk 3]
```diff
@@ -1113,19 +1210,21 @@ void CodeGen_GLSL::test() {
...
     check(Halide::print(3.0f), "float $ = 3.0;\n");
 
     // Test rounding behavior of integer division.
-    check(Variable::make(Int(32), "x") / Variable::make(Int(32), "y"),
-          "float $ = float($x);\n"
-          "float $ = float($y);\n"
-          "float $ = $ / $;\n"
-          "float $ = floor($);\n"
-          "int $ = int($);\n");
+    // The latest version of integer division it too complicated to list here
```
[the remark this answers is not in the document]
Comment (xndcn) [reply src/CodeGen_OpenGL_Dev.cpp]: Fixed, thanks!

**Comment by xndcn** [comment]
> Note that apps/opengl_test is failing because it apparently requires X11 to be functional, which isn't the case on our buildbots

It may be fixed to ignore the X11 library in MacOS and try to use the EGL feature in Linux to avoid the "Could not open X11 display" error in Buildbot headless environment.
I'm try to fix it and will update later.

**Comment by xndcn** [comment]
Add EGL feature for apps/glsl in Linux and remove X11 linking if X11 is not found since it is not necessary in MacOS.
Hope it can fix errors of apps/glsl in Buildbot environment.

File: cmake/HalideGeneratorHelpers.cmake [hunk 4]
```diff
@@ -343,21 +343,27 @@ endfunction()
...
+        if (NOT "${ARGN}" MATCHES "egl" AND NOT TARGET X11::X11)
             find_package(X11)
             if (NOT X11_FOUND)
                 message(AUTHOR_WARNING "X11 dependency not found on system.")
             endif ()
         endif ()
-        target_link_libraries(${TARGET} ${VISIBILITY} X11::X11)
+        if (X11_FOUND)
+            target_link_libraries(${TARGET} ${VISIBILITY} X11::X11)
+        endif ()
```
Comment (alexreinking) [inline cmake/HalideGeneratorHelpers.cmake:354]: This is wrong. `X11_FOUND` is set as a cache variable so X11 will be linked to every target _after_ the first one loads X11 (or if it is loaded previously). I think this is what you meant (it seems you intended to link X11 only if "egl" is not in the target)

```cmake
if (NOT "${ARGN}" MATCHES "egl")
    if (NOT TARGET X11::X11)
        find_package(X11 REQUIRED)
        if (NOT X11_FOUND)
            message(AUTHOR_WARNING "X11 dependency not found on system.")
        endif ()
    endif ()
    target_link_libraries(${TARGET} ${VISIBILITY} X11::X11)
endif ()
```

File: cmake/HalideGeneratorHelpers.cmake [hunk 5]
```diff
@@ -343,21 +343,27 @@ endfunction()
...
             if (NOT OPENGL_FOUND)
                 message(AUTHOR_WARNING "OpenGL dependency not found on system.")
             endif ()
         endif ()
-        target_link_libraries(${TARGET} ${VISIBILITY} OpenGL::GL)
+        if ("${ARGN}" MATCHES "egl")
+            target_link_libraries(${TARGET} ${VISIBILITY} OpenGL::EGL)
+        else ()
+            target_link_libraries(${TARGET} ${VISIBILITY} OpenGL::GL)
+        endif ()
```
Comment (alexreinking) [inline cmake/HalideGeneratorHelpers.cmake:366]: This needs some fixing too. No need to run the check because `OpenGL::EGL` is missing if the user didn't ask for EGL.

```cmake
if ("${ARGN}" MATCHES "egl")
    if (NOT TARGET OpenGL::EGL)
        find_package(OpenGL QUIET COMPONENTS EGL)
        if (NOT OPENGL_FOUND)
            message(AUTHOR_WARNING "OpenGL dependency not found on system.")
        endif ()
    endif ()
    target_link_libraries(${TARGET} ${VISIBILITY} OpenGL::EGL)
else ()
    if (NOT TARGET OpenGL::GL)
        find_package(OpenGL QUIET)
        if (NOT OPENGL_FOUND)
            message(AUTHOR_WARNING "OpenGL dependency not found on system.")
        endif ()
    endif ()
    target_link_libraries(${TARGET} ${VISIBILITY} OpenGL::GL)
endif ()
```

**Review by alexreinking — CHANGES_REQUESTED** [review]

File: apps/glsl/CMakeLists.txt [hunk 6]
```diff
@@ -16,6 +16,13 @@ set(CMAKE_CXX_EXTENSIONS NO)
 # Find Halide
 find_package(Halide REQUIRED)
 
+find_package(OpenGL QUIET)
```
Comment (alexreinking) [inline apps/glsl/CMakeLists.txt:19]: Should be:
```cmake
find_package(OpenGL QUIET OPTIONAL_COMPONENTS EGL)
```

**Review by alexreinking — CHANGES_REQUESTED** [review]

**Comment by xndcn** [comment]
@alexreinking Thanks!

**Comment by xndcn** [comment]
@alexreinking I remembered that MacOS did not have EGL but didn't need X11 linking either. Should I add `if ("${ARGN}" MATCHES "linux")` around the X11 dependency?

**Comment by alexreinking** [comment]
> @alexreinking I remembered that MacOS did not have EGL but didn't need X11 linking either. Should I add `if ("${ARGN}" MATCHES "linux")` around the X11 dependency?

Nah, if a user requests EGL on macOS it should blow up. If you want, you can use that check to produce an AUTHOR_WARNING.

**Comment by xndcn** [comment]
> > @alexreinking I remembered that MacOS did not have EGL but didn't need X11 linking either. Should I add `if ("${ARGN}" MATCHES "linux")` around the X11 dependency?
> 
> Nah, if a user requests EGL on macOS it should blow up. If you want, you can use that check to produce an AUTHOR_WARNING.

Not that issue. I mean, on macOS it does not use EGL feature and the generator will fail to link X11 library. Should we add runtime checking around the X11 in CMake?
It also happens in osx-testbench of Buildbot:

**Comment by steven-johnson** [comment]
Looks like this is still failing on OSX with "X11 not found", see https://buildbot.halide-lang.org/master/#/builders/33/builds/72

**Comment by alexreinking** [comment]
> Not that issue. I mean, on macOS it does not use EGL feature and the generator will fail to link X11 library. Should we add runtime checking around the X11 in CMake?

Yeah, then go ahead and add "if linux" around that dependency.

**Comment by xndcn** [comment]
Add "if linux" around the X11 dependency.

**Comment by xndcn** [comment]
@alexreinking It seems that Linux will use `GLX` as OpenGL library which need libX11, while `EGL` or other platforms don't need it.

**Comment by alexreinking** [comment]
Turns out that `if (... MATCHES "linux")` doesn't work when the target is `host-opengl` and the host is Linux.

**Comment by alexreinking** [comment]
Okay there's a bunch of stuff I learned by trying to run this locally.

* The `FindOpenGL` module is weird and we shouldn't use `OPTIONAL_COMPONENTS` with it.
* It is possible to have "found" EGL even if libOpenGL is not found. But this will never work.
* If the user wants `EGL` we should assume Linux because EGL is Linux-only.
* EGL requires the GLVND libraries, so we should link to `OpenGL::OpenGL` and `OpenGL::EGL`
* If the user does not ask for EGL, use `OpenGL::GL` for portability.
* Need to install `libglvnd-dev` and `libegl-dev` to use EGL.

**Comment by alexreinking** [comment]
@xndcn - I reworked the CMake stuff a bit and pushed to your branch, just so you know.

**Comment by alexreinking** [comment]
@xndcn - I added code to load `libEGL.so` in the JIT module so that AOT targets like `host-cuda` don't break when detecting CUDA capability.

**Comment by steven-johnson** [comment]
Build finally green, landing

**Review by alexreinking — APPROVED** [review]

**Comment by alexreinking** [comment]
@xndcn - we're having issues on our newer buildbots where EGL is getting the wrong default display. Basically, it's picking the GBM platform instead of the NVidia device platform. It's looking for a pbuffer-enabled surface, but only "win" is available through GBM. Any ideas how we can fix this?

Here's the `eglinfo` output from the bot:

```
$ eglinfo 
EGL client extensions string:
    EGL_EXT_platform_base EGL_EXT_device_base EGL_EXT_device_enumeration
    EGL_EXT_device_query EGL_KHR_client_get_all_proc_addresses
    EGL_EXT_client_extensions EGL_KHR_debug EGL_KHR_platform_x11
    EGL_EXT_platform_x11 EGL_EXT_platform_device EGL_EXT_platform_wayland
    EGL_KHR_platform_wayland EGL_MESA_platform_gbm EGL_KHR_platform_gbm
    EGL_MESA_platform_surfaceless

GBM platform:
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_ANDROID_blob_cache EGL_EXT_buffer_age
    EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers
    EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context
    EGL_KHR_create_context_no_error EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap
    EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context
    EGL_MESA_image_dma_buf_export EGL_MESA_query_driver
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0 10 10 10  2  0  0  0 0 0x30335241--         y  y  y     win
0x02 32  0 10 10 10  2 16  0  0 0 0x30335241--         y  y  y     win
0x03 32  0 10 10 10  2 24  0  0 0 0x30335241--         y  y  y     win
0x04 32  0 10 10 10  2 24  8  0 0 0x30335241--         y  y  y     win
0x05 32  0 10 10 10  2 32  0  0 0 0x30335241--         y  y  y     win
0x06 32  0 10 10 10  2  0  0  4 1 0x30335241--         y  y  y     win
0x07 32  0 10 10 10  2 16  0  4 1 0x30335241--         y  y  y     win
0x08 32  0 10 10 10  2 24  0  4 1 0x30335241--         y  y  y     win
0x09 32  0 10 10 10  2 24  8  4 1 0x30335241--         y  y  y     win
0x0a 32  0 10 10 10  2 32  0  4 1 0x30335241--         y  y  y     win
0x0b 30  0 10 10 10  0  0  0  0 0 0x30335258--         y  y  y     win
0x0c 30  0 10 10 10  0 16  0  0 0 0x30335258--         y  y  y     win
0x0d 30  0 10 10 10  0 24  0  0 0 0x30335258--         y  y  y     win
0x0e 30  0 10 10 10  0 24  8  0 0 0x30335258--         y  y  y     win
0x0f 30  0 10 10 10  0 32  0  0 0 0x30335258--         y  y  y     win
0x10 30  0 10 10 10  0  0  0  4 1 0x30335258--         y  y  y     win
0x11 30  0 10 10 10  0 16  0  4 1 0x30335258--         y  y  y     win
0x12 30  0 10 10 10  0 24  0  4 1 0x30335258--         y  y  y     win
0x13 30  0 10 10 10  0 24  8  4 1 0x30335258--         y  y  y     win
0x14 30  0 10 10 10  0 32  0  4 1 0x30335258--         y  y  y     win
0x15 32  0  8  8  8  8  0  0  0 0 0x34325241--         y  y  y     win
0x16 32  0  8  8  8  8 16  0  0 0 0x34325241--         y  y  y     win
0x17 32  0  8  8  8  8 24  0  0 0 0x34325241--         y  y  y     win
0x18 32  0  8  8  8  8 24  8  0 0 0x34325241--         y  y  y     win
0x19 32  0  8  8  8  8 32  0  0 0 0x34325241--         y  y  y     win
0x1a 32  0  8  8  8  8  0  0  4 1 0x34325241--         y  y  y     win
0x1b 32  0  8  8  8  8 16  0  4 1 0x34325241--         y  y  y     win
0x1c 32  0  8  8  8  8 24  0  4 1 0x34325241--         y  y  y     win
0x1d 32  0  8  8  8  8 24  8  4 1 0x34325241--         y  y  y     win
0x1e 32  0  8  8  8  8 32  0  4 1 0x34325241--         y  y  y     win
0x1f 24  0  8  8  8  0  0  0  0 0 0x34325258--         y  y  y     win
0x20 24  0  8  8  8  0 16  0  0 0 0x34325258--         y  y  y     win
0x21 24  0  8  8  8  0 24  0  0 0 0x34325258--         y  y  y     win
0x22 24  0  8  8  8  0 24  8  0 0 0x34325258--         y  y  y     win
0x23 24  0  8  8  8  0 32  0  0 0 0x34325258--         y  y  y     win
0x24 24  0  8  8  8  0  0  0  4 1 0x34325258--         y  y  y     win
0x25 24  0  8  8  8  0 16  0  4 1 0x34325258--         y  y  y     win
0x26 24  0  8  8  8  0 24  0  4 1 0x34325258--         y  y  y     win
0x27 24  0  8  8  8  0 24  8  4 1 0x34325258--         y  y  y     win
0x28 24  0  8  8  8  0 32  0  4 1 0x34325258--         y  y  y     win
0x29 16  0  5  6  5  0  0  0  0 0 0x36314752--         y  y  y     win
0x2a 16  0  5  6  5  0 16  0  0 0 0x36314752--         y  y  y     win
0x2b 16  0  5  6  5  0 24  0  0 0 0x36314752--         y  y  y     win
0x2c 16  0  5  6  5  0 24  8  0 0 0x36314752--         y  y  y     win
0x2d 16  0  5  6  5  0 32  0  0 0 0x36314752--         y  y  y     win
0x2e 16  0  5  6  5  0  0  0  4 1 0x36314752--         y  y  y     win
0x2f 16  0  5  6  5  0 16  0  4 1 0x36314752--         y  y  y     win
0x30 16  0  5  6  5  0 24  0  4 1 0x36314752--         y  y  y     win
0x31 16  0  5  6  5  0 24  8  4 1 0x36314752--         y  y  y     win
0x32 16  0  5  6  5  0 32  0  4 1 0x36314752--         y  y  y     win

Wayland platform:
eglinfo: eglInitialize failed

X11 platform:
EGL API version: 1.5
EGL vendor string: Mesa Project
EGL version string: 1.5
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_EXT_create_context_robustness EGL_KHR_cl_event2
    EGL_KHR_config_attribs EGL_KHR_context_flush_control
    EGL_KHR_create_context EGL_KHR_create_context_no_error
    EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses
    EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image
    EGL_KHR_gl_texture_cubemap_image EGL_KHR_image_base
    EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image
    EGL_MESA_query_driver
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8  0  0  0 0 0x21TC      a  y  y  y     win,pb,pix
0x02 32  0  8  8  8  8 16  0  0 0 0x21TC      a  y  y  y     win,pb,pix
0x03 32  0  8  8  8  8 24  0  0 0 0x21TC      a  y  y  y     win,pb,pix
0x04 32  0  8  8  8  8 24  8  0 0 0x21TC      a  y  y  y     win,pb,pix
0x05 32  0  8  8  8  8 32  0  0 0 0x21TC      a  y  y  y     win,pb,pix
0x06 32  0  8  8  8  8  0  0  4 1 0x21TC      a  y  y  y     win,pix
0x07 32  0  8  8  8  8 16  0  4 1 0x21TC      a  y  y  y     win,pix
0x08 32  0  8  8  8  8 24  0  4 1 0x21TC      a  y  y  y     win,pix
0x09 32  0  8  8  8  8 24  8  4 1 0x21TC      a  y  y  y     win,pix
0x0a 32  0  8  8  8  8 32  0  4 1 0x21TC      a  y  y  y     win,pix
0x0b 24  0  8  8  8  0  0  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x0c 24  0  8  8  8  0 16  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x0d 24  0  8  8  8  0 24  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x0e 24  0  8  8  8  0 24  8  0 0 0x21TC      y  y  y  y     win,pb,pix
0x0f 24  0  8  8  8  0 32  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x10 24  0  8  8  8  0  0  0  4 1 0x21TC      y  y  y  y     win,pix
0x11 24  0  8  8  8  0 16  0  4 1 0x21TC      y  y  y  y     win,pix
0x12 24  0  8  8  8  0 24  0  4 1 0x21TC      y  y  y  y     win,pix
0x13 24  0  8  8  8  0 24  8  4 1 0x21TC      y  y  y  y     win,pix
0x14 24  0  8  8  8  0 32  0  4 1 0x21TC      y  y  y  y     win,pix
0x15 32  0  8  8  8  8  0  0  0 0 0x22DC      a  y  y  y     win,pb,pix
0x16 32  0  8  8  8  8 16  0  0 0 0x22DC      a  y  y  y     win,pb,pix
0x17 32  0  8  8  8  8 24  0  0 0 0x22DC      a  y  y  y     win,pb,pix
0x18 32  0  8  8  8  8 24  8  0 0 0x22DC      a  y  y  y     win,pb,pix
0x19 32  0  8  8  8  8 32  0  0 0 0x22DC      a  y  y  y     win,pb,pix
0x1a 32  0  8  8  8  8  0  0  4 1 0x22DC      a  y  y  y     win,pix
0x1b 32  0  8  8  8  8 16  0  4 1 0x22DC      a  y  y  y     win,pix
0x1c 32  0  8  8  8  8 24  0  4 1 0x22DC      a  y  y  y     win,pix
0x1d 32  0  8  8  8  8 24  8  4 1 0x22DC      a  y  y  y     win,pix
0x1e 32  0  8  8  8  8 32  0  4 1 0x22DC      a  y  y  y     win,pix
0x1f 24  0  8  8  8  0  0  0  0 0 0x22DC      y  y  y  y     win,pb,pix
0x20 24  0  8  8  8  0 16  0  0 0 0x22DC      y  y  y  y     win,pb,pix
0x21 24  0  8  8  8  0 24  0  0 0 0x22DC      y  y  y  y     win,pb,pix
0x22 24  0  8  8  8  0 24  8  0 0 0x22DC      y  y  y  y     win,pb,pix
0x23 24  0  8  8  8  0 32  0  0 0 0x22DC      y  y  y  y     win,pb,pix
0x24 24  0  8  8  8  0  0  0  4 1 0x22DC      y  y  y  y     win,pix
0x25 24  0  8  8  8  0 16  0  4 1 0x22DC      y  y  y  y     win,pix
0x26 24  0  8  8  8  0 24  0  4 1 0x22DC      y  y  y  y     win,pix
0x27 24  0  8  8  8  0 24  8  4 1 0x22DC      y  y  y  y     win,pix
0x28 24  0  8  8  8  0 32  0  4 1 0x22DC      y  y  y  y     win,pix

Device platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
EGL extensions string:
    EGL_EXT_buffer_age EGL_EXT_client_sync
    EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import
    EGL_EXT_image_dma_buf_import_modifiers EGL_MESA_image_dma_buf_export
    EGL_EXT_output_base EGL_EXT_output_drm EGL_EXT_protected_content
    EGL_EXT_stream_consumer_egloutput EGL_EXT_stream_acquire_mode
    EGL_EXT_sync_reuse EGL_IMG_context_priority EGL_KHR_config_attribs
    EGL_KHR_create_context_no_error EGL_KHR_context_flush_control
    EGL_KHR_create_context EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_partial_update
    EGL_KHR_swap_buffers_with_damage EGL_KHR_no_config_context
    EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image
    EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base
    EGL_KHR_reusable_sync EGL_KHR_stream EGL_KHR_stream_attrib
    EGL_KHR_stream_consumer_gltexture EGL_KHR_stream_cross_process_fd
    EGL_KHR_stream_fifo EGL_KHR_stream_producer_eglsurface
    EGL_KHR_surfaceless_context EGL_KHR_wait_sync EGL_NV_nvrm_fence_sync
    EGL_NV_quadruple_buffer EGL_NV_stream_consumer_eglimage
    EGL_NV_stream_cross_display EGL_NV_stream_cross_object
    EGL_NV_stream_cross_process EGL_NV_stream_cross_system
    EGL_NV_stream_dma EGL_NV_stream_flush EGL_NV_stream_metadata
    EGL_NV_stream_remote EGL_NV_stream_reset EGL_NV_stream_socket
    EGL_NV_stream_socket_inet EGL_NV_stream_socket_unix
    EGL_NV_stream_sync EGL_NV_stream_fifo_next
    EGL_NV_stream_fifo_synchronous EGL_NV_stream_consumer_gltexture_yuv
    EGL_NV_stream_attrib EGL_NV_stream_origin EGL_NV_system_time
    EGL_NV_output_drm_flip_event EGL_NV_triple_buffer
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8 24  8  0 0 0x00--         y  y  y     pb,str
0x02 32  0  8  8  8  8 24  0  0 0 0x00--         y  y  y     pb,str
0x03 32  0  8  8  8  8  0  8  0 0 0x00--         y  y  y     pb,str
0x04 32  0  8  8  8  8  0  0  0 0 0x00--         y  y  y     pb,str
0x05 32  0  8  8  8  8 24  8  2 1 0x00--         y  y  y     pb,str
0x06 32  0  8  8  8  8 24  0  2 1 0x00--         y  y  y     pb,str
0x07 32  0  8  8  8  8  0  8  2 1 0x00--         y  y  y     pb,str
0x08 32  0  8  8  8  8  0  0  2 1 0x00--         y  y  y     pb,str
0x09 32  0  8  8  8  8 24  8  4 1 0x00--         y  y  y     pb,str
0x0a 32  0  8  8  8  8 24  8  4 1 0x00--         y  y  y     pb,str
0x0b 32  0  8  8  8  8 24  0  4 1 0x00--         y  y  y     pb,str
0x0c 32  0  8  8  8  8 24  0  4 1 0x00--         y  y  y     pb,str
0x0d 32  0  8  8  8  8  0  8  4 1 0x00--         y  y  y     pb,str
0x0e 32  0  8  8  8  8  0  8  4 1 0x00--         y  y  y     pb,str
0x0f 32  0  8  8  8  8  0  0  4 1 0x00--         y  y  y     pb,str
0x10 32  0  8  8  8  8  0  0  4 1 0x00--         y  y  y     pb,str
0x11 32  0  8  8  8  8 24  8  8 1 0x00--         y  y  y     pb,str
0x12 32  0  8  8  8  8 24  0  8 1 0x00--         y  y  y     pb,str
0x13 32  0  8  8  8  8  0  8  8 1 0x00--         y  y  y     pb,str
0x14 32  0  8  8  8  8  0  0  8 1 0x00--         y  y  y     pb,str
0x15 24  0  8  8  8  0 24  8  0 0 0x00--         y  y  y     pb,str
0x16 24  0  8  8  8  0 24  0  0 0 0x00--         y  y  y     pb,str
0x17 24  0  8  8  8  0  0  8  0 0 0x00--         y  y  y     pb,str
0x18 24  0  8  8  8  0  0  0  0 0 0x00--         y  y  y     pb,str
0x19 24  0  8  8  8  0 24  8  2 1 0x00--         y  y  y     pb,str
0x1a 24  0  8  8  8  0 24  0  2 1 0x00--         y  y  y     pb,str
0x1b 24  0  8  8  8  0  0  8  2 1 0x00--         y  y  y     pb,str
0x1c 24  0  8  8  8  0  0  0  2 1 0x00--         y  y  y     pb,str
0x1d 24  0  8  8  8  0 24  8  4 1 0x00--         y  y  y     pb,str
0x1e 24  0  8  8  8  0 24  8  4 1 0x00--         y  y  y     pb,str
0x1f 24  0  8  8  8  0 24  0  4 1 0x00--         y  y  y     pb,str
0x20 24  0  8  8  8  0 24  0  4 1 0x00--         y  y  y     pb,str
0x21 24  0  8  8  8  0  0  8  4 1 0x00--         y  y  y     pb,str
0x22 24  0  8  8  8  0  0  8  4 1 0x00--         y  y  y     pb,str
0x23 24  0  8  8  8  0  0  0  4 1 0x00--         y  y  y     pb,str
0x24 24  0  8  8  8  0  0  0  4 1 0x00--         y  y  y     pb,str
0x25 24  0  8  8  8  0 24  8  8 1 0x00--         y  y  y     pb,str
0x26 24  0  8  8  8  0 24  0  8 1 0x00--         y  y  y     pb,str
0x27 24  0  8  8  8  0  0  8  8 1 0x00--         y  y  y     pb,str
0x28 24  0  8  8  8  0  0  0  8 1 0x00--         y  y  y     pb,str
0x29 16  0  5  6  5  0 24  8  0 0 0x00--         y  y  y     pb,str
0x2a 16  0  5  6  5  0 24  0  0 0 0x00--         y  y  y     pb,str
0x2b 16  0  5  6  5  0 16  0  0 0 0x00--         y  y  y     pb,str
0x2c 16  0  5  6  5  0  0  8  0 0 0x00--         y  y  y     pb,str
0x2d 16  0  5  6  5  0  0  0  0 0 0x00--         y  y  y     pb,str
0x2e 16  0  5  6  5  0 24  8  2 1 0x00--         y  y  y     pb,str
0x2f 16  0  5  6  5  0 24  0  2 1 0x00--         y  y  y     pb,str
0x30 16  0  5  6  5  0 16  0  2 1 0x00--         y  y  y     pb,str
0x31 16  0  5  6  5  0  0  8  2 1 0x00--         y  y  y     pb,str
0x32 16  0  5  6  5  0  0  0  2 1 0x00--         y  y  y     pb,str
0x33 16  0  5  6  5  0 24  8  4 1 0x00--         y  y  y     pb,str
0x34 16  0  5  6  5  0 24  8  4 1 0x00--         y  y  y     pb,str
0x35 16  0  5  6  5  0 24  0  4 1 0x00--         y  y  y     pb,str
0x36 16  0  5  6  5  0 24  0  4 1 0x00--         y  y  y     pb,str
0x37 16  0  5  6  5  0 16  0  4 1 0x00--         y  y  y     pb,str
0x38 16  0  5  6  5  0 16  0  4 1 0x00--         y  y  y     pb,str
0x39 16  0  5  6  5  0  0  8  4 1 0x00--         y  y  y     pb,str
0x3a 16  0  5  6  5  0  0  8  4 1 0x00--         y  y  y     pb,str
0x3b 16  0  5  6  5  0  0  0  4 1 0x00--         y  y  y     pb,str
0x3c 16  0  5  6  5  0  0  0  4 1 0x00--         y  y  y     pb,str
0x3d 16  0  5  6  5  0 24  8  8 1 0x00--         y  y  y     pb,str
0x3e 16  0  5  6  5  0 24  0  8 1 0x00--         y  y  y     pb,str
0x3f 16  0  5  6  5  0 16  0  8 1 0x00--         y  y  y     pb,str
0x40 16  0  5  6  5  0  0  8  8 1 0x00--         y  y  y     pb,str
0x41 16  0  5  6  5  0  0  0  8 1 0x00--         y  y  y     pb,str
```
