### PR TITLE
Fix segfault in RDom's operator<<

### LINKED ISSUE #8663: SIGSEGV when using RDom default constructor from Python
Hi Team! This code SIGSEGV's on my Mac:

```python
from halide import RDom
RDom()
```
I'm using a local build of halide on main (freshly built a few minutes a go) with Python 3.11.13

The behavior I was expecting was either:

* A `TypeError` exception being raised giving a list of supported constructors. Try `RDom(0)` for an example.
* the invocation of the default constructor as [documented here](https://halide-lang.org/docs/class_halide_1_1_r_dom.html#a67f1c2b2c0c169dfa82f9698b302d659).

To be clear I *don't* have a use case for the default constructor and would be content with the `TypeError`. I stumbled into this accidentally.

Thanks!

### PR DESCRIPTION
**Pull request by alexreinking**
We were missing a check for `RDom::defined()` here. Slight tweaking of the format to make more sense in the Python repl (which is where this was discovered).

Fixes #8663

### CODE REVIEW

File: src/RDom.cpp [hunk 1]
```diff
@@ -260,16 +260,19 @@ std::ostream &operator<<(std::ostream &stream, const RVar &v) {
...
+    if (!dom.defined()) {
+        return stream << "RDom()";
+    }
+
     stream << "RDom(\n";
     for (int i = 0; i < dom.dimensions(); i++) {
         stream << "  " << dom[i] << "\n";
     }
     stream << ")";
-    Expr pred = simplify(dom.domain().predicate());
```
Comment (mcourteaux) [inline src/RDom.cpp:268]: Why remove the simplify?

Comment (alexreinking) [reply src/RDom.cpp:268]: Because it lies about the state of the object in what's supposed to be debugging output rather than pretty printing output. Also, it's slow.

Comment (mcourteaux) [reply src/RDom.cpp:268]: Makes sense. Thanks for your response. I'm still learning :)

**Review by mcourteaux — APPROVED** [review]

File: src/RDom.cpp (hunk 1 above)
Comment (abadams) [reply src/RDom.cpp:268]: It's a printing routine - it should print the IR as it is, not transformed in any way.

**Comment by alexreinking** [comment]
Failures unrelated.
