### PR TITLE
Fix overcompute when compute_at a split rvar that doesn't divide the original extent

### LINKED ISSUE #3036: vectorized loads can overread buffers
TL;DR: vectorized loads can overread an input buffer; not sure of the details yet, capturing an example for starters:

Given a simple pipeline like:

```
    const int vec_size = 4;
    const int width = vec_size * 2 - 1;

    Var x, xi;

    Buffer<float> input_buf(width);
    input_buf.fill(0.f);

    ImageParam input(Float(32), 1, "input");
    input.set(input_buf);

    Func tmp("tmp");
    tmp(x) = input(x);

    Func output("output");
    output(x) = tmp(x);

    tmp.compute_at(output, xi);
    output.compute_root()
        .split(x, x, xi, vec_size, TailStrategy::GuardWithIf)
        .vectorize(xi);

    // Set explicit extents just to make .stmt more readable
    // (not necessary for repro)
    input.dim(0).set_min(0).set_extent(width).set_stride(1);
    output.output_buffer().dim(0).set_min(0).set_extent(width).set_stride(1);

    auto b = output.realize(width);
```

This generates .stmt like:

```
  produce output {
    allocate tmp[float32 * 4]
    produce tmp {
      tmp[ramp(0, 1, 4)] = input[ramp(0, 1, 4)]
    }
    output[ramp(0, 1, 4)] = tmp[ramp(0, 1, 4)]
    free tmp
    allocate tmp[float32 * 4]
    produce tmp {
      tmp[ramp(0, 1, 4)] = input[ramp(4, 1, 4)]
    }
    predicate ((x4(4) < ramp(7, -1, 4)))
      output[ramp(4, 1, 4)] = (tmp[ramp(0, 1, 4)] if (x4(4) < ramp(7, -1, 4)))
    free tmp
  }
```

Note that the input buffer is known at compiletime to be 1.75 vectors wide, but rather than the one-dense-and-one-masked-load you'd expect, we get two-dense-and-one-masked.

### PR DESCRIPTION
**Pull request by abadams**
Computation bounds inference didn't really understand guardwithif when it comes to splitting rvars. This issue was causing schedules that overread the input and segfault due to #3036. It would be good to also fix #3036, but as the comments on #3037 show, allocation bounds inference is currently too conservative for this to be feasible.

### CODE REVIEW

**Comment by abadams** [comment]
Apparently I used a magic phrase that will close #3036 when this is merged, so whoever merges this, please reopen #3036.

File: test/correctness/compute_at_split_rvar.cpp [hunk 1]
```diff
@@ -16,6 +16,7 @@ extern "C" DLLEXPORT int count(int x) {
 HalideExtern_1(int, count, int);
 
 int main(int argc, char **argv) {
+#if 0
```
Comment (steven-johnson) [inline test/correctness/compute_at_split_rvar.cpp]: ...did you mean to leave this disabled?

**Comment by steven-johnson** [comment]
LGTM

**Comment by zvookin** [comment]
Build failure looks like a performance thing that is almost certainly a flake.

**Comment by steven-johnson** [comment]
FYI: this appears to have caused some dramatic slowdowns in at least one Google pipeline (~3x on ARM, ~2x on desktop); I'm going to dive in further to see more info as to why.

**Comment by steven-johnson** [comment]
The code change that is slowing things down is that several stages that were formerly something like:

```
allocate f[float32 * 24]
produce f {
  f[ramp(0, 1, 8)] = ...expr...
  f[ramp(8, 1, 8)] = ...expr...
  f[ramp(16, 1, 8)] = ...expr...
}
```

become something like

```
allocate f[float32 * expr-involving-RDom-dimensions]
produce f {
  for (f.s0.x.x, 0, t240) {
    f[ramp(((f.s0.x.x + t241)*8), 1, 8)] = ...expr...
  }

  let t243 = expr-involving-RDom-dimensions
  let t242 = expr-involving-RDom-dimensions
  for (f.s0.x.x, 0, t242) {
    f[ramp(((f.s0.x.x + t243)*8), 1, 8)] = ...expr...
  }
  let t246 = expr-involving-RDom-dimensions
  let t245 = expr-involving-RDom-dimensions
  for (f.s0.x.x, 0, t246) {
    f[ramp(((f.s0.x.x + t245)*8), 1, 8)] = ...expr...
  }
}
```

**Comment by abadams** [comment]
I have also seen it cause problems (e.g. #3519) I'll see if I can have it only trigger in the cases where it's necessary.

**Comment by abadams** [comment]
Even then it causes problems. The basic issue is that if you're compute_at a tile of something that uses a GuardWithIf to make those tiles, then the amount required is not a constant. In the steady state you need whatever a full tile would consume, but at the end you have this little partial tile of the consumer, and you only require a partial tile of the producer too. So the allocation are the loops are suddenly non-constant.

Previously we effectively just rounded up the producer and computed a full tile at the end, but if the producer reads from an input, that means guardwithif doesn't save you from needing an aligned input size.

**Comment by abadams** [comment]
You may be able to restore the old behavior with judicious application of bound_extent on your f.

**Comment by steven-johnson** [comment]
Ah, yep, that smells right: the code in question is doing something like
```
  Expr aligned_input_width =(width_in_ / vector_size()) * vector_size(); 
  RDom r(0, aligned_input_width(), 0, height_in_);
```
I'll experiment with bound_extent.

**Comment by steven-johnson** [comment]
Unfortunately, adding the `bound_extent()` actually makes the problem worse (now we're redundantly computing each intermediate stage on a per-line basis), but the pipeline in question is a little more complex than my simple example. Let me see if I can reduce it to something simple.

**Comment by steven-johnson** [comment]
OK, so the interesting part here is that the de-optimized producer isn't reading directly from an input, but rather, from the pure stage of a Func (for consumption by an update stage), so Halide is in total control of the buffer sizes. Here's a snippet of code that demonstrates the issue:

```
    // Algorithm

    Var x;

    ImageParam depth_in(Int(32), 1);

    const int32_t vector_size = 8;
    Expr aligned_width = (depth_in.width() / vector_size) * vector_size;

    Func new_depth;
    new_depth(x) = random_int();

    RDom r(0, aligned_width);

    Func depth_out;
    depth_out(x) = 0;
    depth_out(r.x) = select(new_depth(r.x) > depth_out(r.x),
                            new_depth(r.x),
                            undef<int>());

    // Schedule
    // (The idea here is to split new_depth into vector-sized chunks
    // to compute each exactly once)

    RVar xo("xo"), xi("xi");

    depth_out
        .bound(x, 0, aligned_width)
        .vectorize(x, vector_size)
        .update(0)
            .split(r.x, xo, xi, vector_size);

    new_depth
        .bound(x, 0, aligned_width)
        .compute_at(depth_out, xo)
        .vectorize(x, vector_size);

    // Realization
    // (Note that the input and output widths must be a multiple of vector_width)

    constexpr int kEdge = 128;

    Buffer<int> depth_in_buf(kEdge);
    std::mt19937 rng(0);
    depth_in_buf.for_each_value([&rng](int &value) {
        value = (int) rng();
    });

    depth_in.set(depth_in_buf);

    Buffer<int> depth_out_buf = depth_out.realize(kEdge);
```

Before this change, this resulted in something like:

```
  produce depth_out {
    let t14 = (depth_in.extent.0/8)
    for (depth_out.s0.x.x, 0, t14) {
      depth_out[ramp((depth_out.s0.x.x*8), 1, 8)] = x8(0)
    }
    let t15 = (depth_in.extent.0/8)
    for (depth_out.s1.r$x.xo, 0, t15) {
      allocate new_depth[int32 * 8]
      produce new_depth {
        new_depth[ramp(0, 1, 8)] = int32x8(((((uint32x8(ramp((depth_out.s1.r$x.xo*8), 1, 8))*x8((uint32)1040796640)) + x8((uint32)2707588617))*(uint32x8(ramp((depth_out.s1.r$x.xo*8), 1, 8)) + x8((uint32)1773003132))) + x8((uint32)576942909)))
      }
      consume new_depth {
        let t16 = (depth_out.s1.r$x.xo*8)
        for (depth_out.s1.r$x.xi, 0, 8) {
          if ((depth_out[(depth_out.s1.r$x.xi + t16)] < new_depth[depth_out.s1.r$x.xi])) {
            depth_out[(depth_out.s1.r$x.xi + t16)] = new_depth[depth_out.s1.r$x.xi]
          }
        }
      }
      free new_depth
    }
  }

  ```

i.e., we were producing and consuming new_depth a single vector at a time. After this PR, this code instead produces something like:

```
  produce depth_out {
    let t18 = (depth_in.extent.0/8)
    for (depth_out.s0.x.x, 0, t18) {
      depth_out[ramp((depth_out.s0.x.x*8), 1, 8)] = x8(0)
    }
    let t22 = (depth_in.extent.0/8)
    let t23 = (t22*8)
    for (depth_out.s1.r$x.xo, 0, t22) {
      let depth_out.s1.r$x.max_1.s = min((depth_out.s1.r$x.xo + 1), t22)
      assert((depth_out.s1.r$x.max_1.s <= t22), halide_error_explicit_bounds_too_small("x", "new_depth", 0, (t23 + -1), (depth_out.s1.r$x.xo*8), ((depth_out.s1.r$x.max_1.s*8) + -1)))
      assert(((depth_out.s1.r$x.xo + 1) <= t22), halide_error_explicit_bounds_too_small("x", "new_depth", 0, (t23 + -1), 0, ((max((depth_out.s1.r$x.xo + 1), t22)*8) + -1)))
      allocate new_depth[int32 * t23]
      produce new_depth {
        for (new_depth.s0.x.x, 0, t22) {
          new_depth[ramp((new_depth.s0.x.x*8), 1, 8)] = int32x8(((((uint32x8(ramp((new_depth.s0.x.x*8), 1, 8))*x8((uint32)1040796640)) + x8((uint32)2707588617))*(uint32x8(ramp((new_depth.s0.x.x*8), 1, 8)) + x8((uint32)1773003132))) + x8((uint32)576942909)))
        }
      }
      consume new_depth {
        let t24 = (depth_out.s1.r$x.xo*8)
        for (depth_out.s1.r$x.xi, 0, 8) {
          if ((depth_out[(depth_out.s1.r$x.xi + t24)] < new_depth[(depth_out.s1.r$x.xi + t24)])) {
            depth_out[(depth_out.s1.r$x.xi + t24)] = new_depth[(depth_out.s1.r$x.xi + t24)]
          }
        }
      }
      free new_depth
    }
  }
```

...which is now producing new_depth a line at a time instead of a vector at a time.

**Comment by steven-johnson** [comment]
(Correction: the "after" case isn't a line at a time -- it's still a vector at a time -- but it is no longer able to statically prove that it's a single vector, so it has the overhead of a variable-length allocation and loop.)

**Comment by steven-johnson** [comment]
Answering my own question: yeah, `bound_extent()` is the thing here; changing the schedule to

```
    new_depth
        .bound_extent(x, vector_size)
        .compute_at(depth_out, xo)
        .vectorize(x, vector_size);
```

Seems to restore the behavior we want.
