### PR TITLE
Work around an LLVM bug in widening casts of loads in wasm

### LINKED ISSUE #8928: Fuzz error: correctness/lossless_cast
```
HL_JIT_TARGET=wasm-32-wasmrt-wasm_simd128
HL_TARGET=wasm-32-wasmrt-wasm_simd128
#CTEST_RESOURCE_GROUP_COUNT=
/Users/halidenightly/build_bot/worker/halide-testbranch-main-llvm_main-x86-64-osx-cmake/halide-build/test/correctness/correctness_lossless_cast
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 560.
Fuzz testing with root seed 1769885050
```

From https://buildbot.halide-lang.org/master/#/builders/260/builds/378

### PR DESCRIPTION
**Pull request by abadams**
Fixes #8928

Pulls in the optimization_fence helper from #8925

### CODE REVIEW

**Comment by abadams** [comment]
LLVM bug filed as https://github.com/llvm/llvm-project/issues/184676

File: src/CodeGen_WebAssembly.cpp [hunk 1]
```diff
@@ -177,6 +177,32 @@ void CodeGen_WebAssembly::visit(const Cast *op) {
...
             return;
         }
+
+        // Work around an LLVM bug where
+        // WebAssemblyTargetLowering::isVectorLoadExtDesirable assumes the
+        // operand of a vector extend is always a load, but LLVM's optimizer may
+        // insert a freeze node between the load and the extend, causing a
+        // cast<LoadSDNode> assertion failure. Use an optimization fence to
+        // prevent the DAG combiner from seeing through to the load.  See
+        // https://github.com/halide/Halide/issues/8928
```
Comment (alexreinking) [inline src/CodeGen_WebAssembly.cpp]: Can you also put a reference to the LLVM issue here?
