### PR TITLE
Fix two compute_with bugs.

### LINKED ISSUE #8149: Getting InternalError with a combination of compute_with, and reductions that use functions with update definitions
This example program
```c++
#include "Halide.h"

using namespace Halide;

int main(int argc, char **argv){
  Func denominator_inter("denominator_inter");
  Func numerator("numerator"), denominator("denominator");
  Var i("i"), si("si"), vis("vis");

  numerator(si) = 0;
  denominator(si) = 0;
  RDom rv(0, 10, "rv");

  denominator_inter(i, vis) = 0;
  denominator_inter(0, vis) = 1 + vis;
  denominator(rv) += denominator_inter(0, rv);

  numerator(rv) += rv;
  numerator.compute_root();
  denominator.compute_root();
  denominator.update().compute_with(numerator.update(), rv);

  Func next("next");
  next(si) = numerator(si) / denominator(si);

  try{
    Target target = get_target_from_environment();
    target.set_feature(Target::Debug);
    next.compile_to_static_library("TestHalide.c", {}, "Test", target);
  } catch (Halide::Error &e){
    std::cerr << "Halide Error: " << e.what() << std::endl;
    __throw_exception_again;
  } 
}
```

throws an internal error:
```
Halide Error: Internal Error at /home/halidenightly/build_bot/worker/halide-nightly-release_17-x86-64-linux-cmake/halide-source/src/CodeGen_LLVM.cpp:1293 triggered by user code at : Symbol not found: denominator.s1.rv$x
The following names are in scope:
{
  ::Test
  denominator
  next
  next.buffer
  next.device_dirty
  next.dimensions
  next.extent.0
  next.min.0
  next.stride.0
  next.type
  numerator
  numerator.s1.rv$x
  numerator.si.extent_realized
  t12
}


```

whilst I believe this would be a valid program.

I've attached the output when running this with `HL_DEBUG_CODEGEN=2`

[out.txt](https://github.com/halide/Halide/files/14564859/out.txt)

I'm using the latest released version 17.0.1.

### PR DESCRIPTION
**Pull request by abadams**
This PR fixes a bug in compute_with, and another bug I found while fixing it (we could really use a compute_with fuzzer).

The first bug is that you can get into situations where the bounds of a producer func will refer directly to the loop variable of a consumer func, where the consumer is in a compute_with fused group. In main, that loop variable may not be defined because fused loop names have been rewritten to include the token ".fused.". This PR adds let stmts to define it just inside the fused loop body.

The second bug is that not all parent loops in compute_with fused groups were having their bounds expanded to cover the region to be computed of all children, because the logic for deciding which loops to expand only considered the non-specialized pure definition. So e.g. compute_with applied to an update stage would fail to compute values of the child Func where they do not overlap with the parent Func. This PR visits all definitions of the parent Func of the fused group, instead of just the unspecialized pure definition of the parent Func.

Fixes #8149

### CODE REVIEW

File: src/ScheduleFunctions.cpp [hunk 1]
```diff
@@ -1748,22 +1817,23 @@ class InjectFunctionRealization : public IRMutator {
...
+        map<string, set<string>> aliases;
 
         for (const auto &func_stage : stage_order) {
             const auto &f = func_stage.first;
 
             if (f.has_extern_definition() && (func_stage.second == 0)) {
-                const Stmt &produceDef = Internal::build_extern_produce(env, f, target);
-                producer = inject_stmt(producer, produceDef, LoopLevel::inlined().lock());
+                const Stmt &produce_def = Internal::build_extern_produce(env, f, target);
+                producer = inject_stmt(producer, produce_def, LoopLevel::inlined().lock());
```
Comment (alexreinking) [inline src/ScheduleFunctions.cpp:1827]: Were these changes done automatically? Why the churn?

**Review by alexreinking — APPROVED** [review]
This looks good... I don't totally understand the `for_type` or `device_api` assignments for the new loops, but it looks like it implements whatever the old policy was.

File: src/ScheduleFunctions.cpp (hunk 1 above)
Comment (abadams) [reply src/ScheduleFunctions.cpp:1827]: This was a drive-by fix to a location variable that didn't match our naming conventions.
